import React, { useEffect, useState } from 'react'
import { useNavigate  } from 'react-router-dom'

import { FaLongArrowAltRight } from "react-icons/fa";
import { FaCheck, FaPlus, FaMinus, FaAnglesRight, FaAngleRight } from "react-icons/fa6";

import GeneralHeader from './GeneralHeader'
import GeneralFooter from './GeneralFooter';
import { PRICING_TABLE } from '../config/Pricing';
import { FAQ } from '../config/FAQ';

export default function LandingPage({authenticated}) {
    const navigate = useNavigate()
    useEffect(() => {
        if (authenticated === true) return navigate('/library')
        return navigate("/")
    // eslint-disable-next-line
    }, [authenticated])
    return (
        <div className="landing">
            <div className="landing-hero-outer">
                <div className="landing-hero-inner common-outer-width">
                    <GeneralHeader/>
                    <h1>Transform <span>comments</span><br/>into <span>content</span></h1>
                    <p>Comment Pilgrim explores the comments section for content ideas and insights based on <span style={{fontWeight: 800}}>real audience opinions.</span></p>

                    <div className="landing-hero-cta">Get Comment Pilgrim<FaLongArrowAltRight/></div>
                    <div className="landing-hero-image">
                        <img src="https://storage.googleapis.com/comment-pilgrim-public/comment-pilgrim-feature-1.png" alt="Comment Pilgrims video feedback page" />
                    </div>
                </div>
            </div>

            <div className="landing-section landing-benefits">
                <div>
                    <h2>Keyword ideas based on the audience's questions, confusions, and requests</h2>
                    <p>Tap into the collective voice of your viewers to uncover the most relevant and engaging topics. Comment Pilgrim transforms any comments section into a goldmine of long-tail keywords, ensuring your content speaks directly to their needs and interests.</p>
                </div>
                <div className="landing-section-image">
                    <img src="https://storage.googleapis.com/comment-pilgrim-public/comment-pilgrim-keywords.png" alt="A list of keywords generated by Comment Pilgrim"/>
                </div>
            </div>

            <div className="landing-section landing-benefits">
                <div className="landing-section-image">
                    <img src="https://storage.googleapis.com/comment-pilgrim-public/comment-pilgrim-library.png" alt="A library of videos that have been analyzed by Comment Pilgrim" />
                </div>
                <div>
                    <h2>Borrow any audience</h2>
                    <p>Amass a collection of perspectives and ideas you can pull from for months at a time, no matter who the original creator is.</p>
                </div>
            </div>
            <div className="landing-section landing-pricing">
                <h2 id="pricing">Plans & Pricing</h2>
                <div className="landing-plans-prices">
                    {PRICING_TABLE.map((plan) => (
                        <PricingPlan plan={plan} isAnnual={false} key={plan._id} />
                    ))}
                </div>
                <div style={{marginTop: "20px", fontSize: "17px", color: "var(--cp-color-subtitles)"}}>Want to try Comment Pilgrim first? Get 5 video reports free when you sign up without a plan</div>
            </div>
            <div className="landing-section landing-benefits">
                <div>
                    <FAQSection/>
                </div>
            </div>
            <div className="landing-section landing-benefits">
                <div>
                    <h2>Create content<br/>without guessing</h2>
                    <p>Don't waste hours creating content your audience doesn't care about. Let Comment Pilgrim figure out exactly what the people want in minutes.</p>
                </div>
                <div className="landing-section-image">
                    <div className="landing-hero-cta">Get started free<FaLongArrowAltRight/></div>
                </div>
            </div>
            <GeneralFooter/>
        </div>
    )
}

function PricingPlan({ plan, isAnnual }) {
    const costs = isAnnual ? plan.cost_annual : plan.cost_monthly;
    const billingPeriod = isAnnual ? 'year' : 'month';
    const featuredPlan = "standard"

    return (
        <div className={`pricing-plan ${plan._id === featuredPlan ? "featured" : "" }`}>
            {plan._id === featuredPlan && <div className="pricing-plan-badge-featured">Recommended</div> }
            <div className="pricing-plan-header">
                <div className="pricing-plan-name">{plan.name}</div>
                <div className="pricing-plan-subtitle">{plan.subtitle}</div>
            </div>
            <div className="pricing-plan-cost">
                <span className="pricing-plan-cost-amount">${costs}</span>
                <span className="pricing-plan-cost-period">/{billingPeriod}</span>
            </div>
            <div className="pricing-plan-description">Included in {plan.name}</div>
            <div className="pricing-plan-benefits">
                <span>
                    <FaCheck /> Library
                </span>
                <span>
                    <FaCheck /> Theme Analysis
                </span>
                <span>
                    <FaCheck /> Featured Comments
                </span>
                <span>
                    <FaCheck /> Audience Sentiment Score
                </span>
                <span>
                    <FaCheck /> Comments Section Summary
                </span>
                <span>
                    <FaCheck /> Long-tail Keyword Generation
                </span>
                <span style={{fontWeight: 800, marginTop: "12px"}}>
                    <FaCheck /> {plan.allowed_videos} Video Reports Per {billingPeriod}
                </span>
            </div>
            <div className="pricing-plan-cta">
                Get {plan.name}
                {plan._id === "standard" && <FaAngleRight/>}
                {plan._id === "agency" && <FaAnglesRight/>}
            </div>
        </div>
    );
}

function FAQSection() {
    const [expandedIndex, setExpandedIndex] = useState(null);

    const toggleFAQ = (index) => {
        if (expandedIndex === index) {
            setExpandedIndex(null);
        } else {
            setExpandedIndex(index);
        }
    };

    return (
        <div className="faq-section">
            <h2>Frequently Asked Questions</h2>
            {FAQ.map((item, index) => (
                <div key={index} className="faq-item">
                    <div className="faq-question" onClick={() => toggleFAQ(index)}>
                        {item.question}
                        {expandedIndex === index ? <FaMinus/> : <FaPlus/>}
                        
                    </div>
                    <div className={`faq-answer ${expandedIndex === index ? 'expanded' : ''}`}>
                        <span>{item.answer}</span>
                    </div>
                </div>
            ))}
        </div>
    );
}